### ISSUE TITLE
v20160822 draft release - npm test failures

### ISSUE THREAD

**Issue by brad4d** [ChadKillingsworth/closure-compiler-npm#33]
I'm getting these failure messages from `npm test` in step 3 of this process:
https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/deployments.md

```
  1) gulp-google-closure-compiler in buffer mode should support passing input globs directly to the compiler:
     Error: 0 position is not passing assertion: expected 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.list=function(){log(this.props.join(", "))};(new WindowInfo).list();\n' to equal 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.WindowInfo_prototype$list=function(){log(this.props.join(", "))};(new WindowInfo).WindowInfo_prototype$list();\n'
      at DestroyableTransform.stream.assertion (node_modules/stream-assert/assertStream.js:24:26)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:102:10)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:623:24)
      at flow (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:632:7)
      at DestroyableTransform.pipeOnReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:664:5)
      at emitReadable_ (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:448:10)
      at emitReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:444:5)
      at readableAddChunk (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:187:9)
      at DestroyableTransform.Readable.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:149:10)
      at DestroyableTransform.Transform.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:101:12)
      at TransformState.afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:80:3)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at Transform.ondata (_stream_readable.js:556:20)
      at readableAddChunk (_stream_readable.js:177:18)
      at Transform.Readable.push (_stream_readable.js:135:10)
      at Transform.push (_stream_transform.js:128:32)
      at Transform.<anonymous> (lib/gulp/index.js:194:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) gulp-google-closure-compiler in buffer mode should include js options before gulp.src files:
     Error: 0 position is not passing assertion: expected 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.list=function(){log(this.props.join(", "))};(new WindowInfo).list();\n' to equal 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.WindowInfo_prototype$list=function(){log(this.props.join(", "))};(new WindowInfo).WindowInfo_prototype$list();\n'
      at DestroyableTransform.stream.assertion (node_modules/stream-assert/assertStream.js:24:26)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:102:10)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:623:24)
      at flow (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:632:7)
      at DestroyableTransform.pipeOnReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:664:5)
      at emitReadable_ (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:448:10)
      at emitReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:444:5)
      at readableAddChunk (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:187:9)
      at DestroyableTransform.Readable.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:149:10)
      at DestroyableTransform.Transform.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:101:12)
      at TransformState.afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:80:3)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at Transform.ondata (_stream_readable.js:556:20)
      at readableAddChunk (_stream_readable.js:177:18)
      at Transform.Readable.push (_stream_readable.js:135:10)
      at Transform.push (_stream_transform.js:128:32)
      at Transform.<anonymous> (lib/gulp/index.js:194:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  3) gulp-google-closure-compiler in buffer mode should support calling the compiler with an arguments array:
     Error: 0 position is not passing assertion: expected 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.list=function(){log(this.props.join(", "))};(new WindowInfo).list();\n' to equal 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.WindowInfo_prototype$list=function(){log(this.props.join(", "))};(new WindowInfo).WindowInfo_prototype$list();\n'
      at DestroyableTransform.stream.assertion (node_modules/stream-assert/assertStream.js:24:26)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:102:10)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:623:24)
      at flow (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:632:7)
      at DestroyableTransform.pipeOnReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:664:5)
      at emitReadable_ (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:448:10)
      at emitReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:444:5)
      at readableAddChunk (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:187:9)
      at DestroyableTransform.Readable.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:149:10)
      at DestroyableTransform.Transform.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:101:12)
      at TransformState.afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:80:3)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at Transform.ondata (_stream_readable.js:556:20)
      at readableAddChunk (_stream_readable.js:177:18)
      at Transform.Readable.push (_stream_readable.js:135:10)
      at Transform.push (_stream_transform.js:128:32)
      at Transform.<anonymous> (lib/gulp/index.js:194:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  4) gulp-google-closure-compiler in buffer mode should compile without gulp.src files when .src() is called:
     Error: 0 position is not passing assertion: expected 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.list=function(){log(this.props.join(", "))};(new WindowInfo).list();\n' to equal 'function log(a){console.log(a)}log("one.js");var WindowInfo=function(){this.props=[]};WindowInfo.prototype.propList=function(){for(var a in window)this.props.push(a)};WindowInfo.prototype.WindowInfo_prototype$list=function(){log(this.props.join(", "))};(new WindowInfo).WindowInfo_prototype$list();\n'
      at DestroyableTransform.stream.assertion (node_modules/stream-assert/assertStream.js:24:26)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:102:10)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:623:24)
      at flow (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:632:7)
      at DestroyableTransform.pipeOnReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:664:5)
      at emitReadable_ (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:448:10)
      at emitReadable (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:444:5)
      at readableAddChunk (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:187:9)
      at DestroyableTransform.Readable.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_readable.js:149:10)
      at DestroyableTransform.Transform.push (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:101:12)
      at TransformState.afterTransform (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at DestroyableTransform._transform (node_modules/stream-assert/index.js:80:3)
      at DestroyableTransform.Transform._read (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at DestroyableTransform.Writable.write (node_modules/stream-assert/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at Transform.ondata (_stream_readable.js:556:20)
      at readableAddChunk (_stream_readable.js:177:18)
      at Transform.Readable.push (_stream_readable.js:135:10)
      at Transform.push (_stream_transform.js:128:32)
      at Transform.<anonymous> (lib/gulp/index.js:194:16)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by ChadKillingsworth** [comment]
I think commit 35bb7c20d58207f469d40eb5efce30051f522ae6 needs reversed.

**Comment by brad4d** [comment]
Thanks, trying that now...

**Comment by brad4d** [comment]
Excellent! All tests pass with that reverted.
